### ISSUE TITLE
enhance circleci logic to not run the merge job on README or `docs` or `examples` updates

### ISSUE THREAD

**Issue by tommyjcarpenter** [merqube/merqube-client-lib#48]
```
README.md
docs/*
examples/*
```

we dont want to run the merge job on changes to these. It will fail, since theres no vbump and the artifact wont push to pypi. 

Either that or we have to move to a more complex release process. I think for now the above is simpler.

**Comment by tommyjcarpenter** [comment]
@jperozo i would like to invite you to tackle this ticket, the hero we need

**Comment by jperozo** [comment]
@tommyjcarpenter ok, I'll work on this next week
